### ISSUE TITLE
今早没有推送发现有错误，重新fork了一遍还是错误，代码如下

### ISSUE THREAD

**Issue by yemaopiqi** [leifengwl/JDRouterPush#21]
Run python JDRouterPush.py
Traceback (most recent call last):
欢迎使用JDRouterPush!
  File "/home/runner/work/JDRouterPush/JDRouterPush/JDRouterPush.py", line 296, in <module>
Request routerActivityInfo failed!
    main()
  File "/home/runner/work/JDRouterPush/JDRouterPush/JDRouterPush.py", line 289, in main
    todayPointDetail()
  File "/home/runner/work/JDRouterPush/JDRouterPush/JDRouterPush.py", line 119, in todayPointDetail
    pointOperateRecordsShow(mac)
  File "/home/runner/work/JDRouterPush/JDRouterPush/JDRouterPush.py", line 135, in pointOperateRecordsShow
    "pageSize": records_num,
NameError: name 'records_num' is not defined
Error: Process completed with exit code 1.

**Comment by leifengwl** [comment]
变量问题导致的，已经修复了，重新更新下JDRouterPush.py，或者重新fork下

**Comment by yemaopiqi** [comment]
> 变量问题导致的，已经修复了，重新更新下JDRouterPush.py，或者重新fork下

弄好了，感谢！
