### ISSUE TITLE
刚才看到更新重新fork了一次，有错误提示，什么问题

### ISSUE THREAD

**Issue by kennylee60** [leifengwl/JDRouterPush#22]
Run python JDRouterPush.py
Traceback (most recent call last):
  File "/home/runner/work/JDRouterPush/JDRouterPush/JDRouterPush.py", line 295, in <module>
欢迎使用JDRouterPush!
Request routerActivityInfo failed!
    main()
  File "/home/runner/work/JDRouterPush/JDRouterPush/JDRouterPush.py", line 288, in main
    todayPointDetail()
  File "/home/runner/work/JDRouterPush/JDRouterPush/JDRouterPush.py", line 125, in todayPointDetail
    JDServiceAPI.getControlDevice(mac,3)
  File "/home/runner/work/JDRouterPush/JDRouterPush/JDServiceAPI.py", line 110, in getControlDevice
    pcdn_list = data["pcdn_list"]
TypeError: string indices must be integers
Error: Process completed with exit code 1.

**Comment by tt5000202** [comment]
同样的问题

**Comment by leifengwl** [comment]
什么设备呢？我这边只有一代64测试没什么问题，我现在解决下

**Comment by leifengwl** [comment]
在JDServiceAPI.py文件里面的第109行(# 插件版本)下面加上一行"print(data)",然后错误信息给我看下,我觉得可能是合作款的原因

**Comment by leifengwl** [comment]
目前已更新  重新fork下  看下是否解决问题

**Comment by tt5000202** [comment]
Run python JDRouterPush.py
欢迎使用JDRouterPush!
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 428, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 472, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1123)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='router-app-api.jdcloud.com', port=443): Max retries exceeded with url: /v1/regions/cn-north-1/todayPointIncome (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1123)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/JDRouterPush/JDRouterPush/JDRouterPush.py", line 295, in <module>
    main()
  File "/home/runner/work/JDRouterPush/JDRouterPush/JDRouterPush.py", line 287, in main
    todayPointIncome()
  File "/home/runner/work/JDRouterPush/JDRouterPush/JDRouterPush.py", line 16, in todayPointIncome
    res = requests.get(GlobalVariable.jd_base_url + "todayPointIncome", headers=GlobalVariable.headers)
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='router-app-api.jdcloud.com', port=443): Max retries exceeded with url: /v1/regions/cn-north-1/todayPointIncome (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1123)')))
Error: Process completed with exit code 1.

**Comment by tt5000202** [comment]
一代64和二代64都有，非合作款，

**Comment by tt5000202** [comment]
刚才fork后执行了两次，第一次是上面那个报错。再次执行，拨错如下
Run python JDRouterPush.py
Traceback (most recent call last):
欢迎使用JDRouterPush!
Request routerActivityInfo failed!
  File "/home/runner/work/JDRouterPush/JDRouterPush/JDRouterPush.py", line 295, in <module>
Request routerActivityInfo failed!
    main()
无法获取插件信息!
  File "/home/runner/work/JDRouterPush/JDRouterPush/JDRouterPush.py", line 288, in main
    todayPointDetail()
  File "/home/runner/work/JDRouterPush/JDRouterPush/JDRouterPush.py", line 125, in todayPointDetail
    JDServiceAPI.getControlDevice(mac,3)
  File "/home/runner/work/JDRouterPush/JDRouterPush/JDServiceAPI.py", line 127, in getControlDevice
    point_info.update(control_device)
TypeError: cannot convert dictionary update sequence element #0 to a sequence
Error: Process completed with exit code 1.

**Comment by leifengwl** [comment]
> 刚才fork后执行了两次，第一次是上面那个报错。再次执行，拨错如下
> Run python JDRouterPush.py
> Traceback (most recent call last):
> 欢迎使用JDRouterPush!
> Request routerActivityInfo failed!
> File "/home/runner/work/JDRouterPush/JDRouterPush/JDRouterPush.py", line 295, in
> Request routerActivityInfo failed!
> main()
> 无法获取插件信息!
> File "/home/runner/work/JDRouterPush/JDRouterPush/JDRouterPush.py", line 288, in main
> todayPointDetail()
> File "/home/runner/work/JDRouterPush/JDRouterPush/JDRouterPush.py", line 125, in todayPointDetail
> JDServiceAPI.getControlDevice(mac,3)
> File "/home/runner/work/JDRouterPush/JDRouterPush/JDServiceAPI.py", line 127, in getControlDevice
> point_info.update(control_device)
> TypeError: cannot convert dictionary update sequence element #0 to a sequence
> Error: Process completed with exit code 1.

把JDServiceAPI.py的第112行改成control_device = {"pluginInfo":False}，或者重新fork下，然后再跑一下看看报什么错

**Comment by kennylee60** [comment]
> 什么设备呢？我这边只有一代64测试没什么问题，我现在解决下
  
我是1代64＋2代128

**Comment by leifengwl** [comment]
> > 什么设备呢？我这边只有一代64测试没什么问题，我现在解决下
> 
> 我是1代64＋2代128

重新拉取下代码  看下是否有问题

**Comment by kennylee60** [comment]
> > > 什么设备呢？我这边只有一代64测试没什么问题，我现在解决下
> > 
> > 
> > 我是1代64＋2代128
> 
> 重新拉取下代码 看下是否有问题

我的没报错了

**Comment by leifengwl** [comment]
> > > > 什么设备呢？我这边只有一代64测试没什么问题，我现在解决下
> > > 
> > > 
> > > 我是1代64＋2代128
> > 
> > 
> > 重新拉取下代码 看下是否有问题
> 
> 我的没报错了

好的

**Comment by tt5000202** [comment]
更新后ok了
