### ISSUE TITLE
看了iss，重新同步了还是不行，显示代码行数有两个不一样

### ISSUE THREAD

**Issue by xy364515640** [leifengwl/JDRouterPush#26]
Run python JDRouterPush.py
Traceback (most recent call last):
欢迎使用JDRouterPush!
  File "/home/runner/work/JDRouterPush/JDRouterPush/JDRouterPush.py", line 295, in <module>
Request routerActivityInfo failed!
    main()
  File "/home/runner/work/JDRouterPush/JDRouterPush/JDRouterPush.py", line 288, in main
无法获取插件信息!
    todayPointDetail()
  File "/home/runner/work/JDRouterPush/JDRouterPush/JDRouterPush.py", line 124, in todayPointDetail
    JDServiceAPI.getControlDevice(mac,2)
  File "/home/runner/work/JDRouterPush/JDRouterPush/JDServiceAPI.py", line 71, in getControlDevice
    result = json.loads(res["result"])
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
Error: Process completed with exit code 1.
一个一代64坐享，一个2代64G

**Comment by leifengwl** [comment]
多次运行都是这个结果吗？

**Comment by leifengwl** [comment]
重新同步下JDServiceAPI.py

**Comment by xy364515640** [comment]
好了，可以了
