### ISSUE TITLE
获取设备失败

### ISSUE THREAD

**Issue by sxx1314** [leifengwl/JDRouterPush#28]
```
Traceback (most recent call last):
  File "JDRouterPush.py", line 295, in <module>
    main()
  File "JDRouterPush.py", line 288, in main
    todayPointDetail()
  File "JDRouterPush.py", line 121, in todayPointDetail
    JDServiceAPI.getListAllUserDevices()
  File "/mnt/mmc0/work/JDRouterPush/JDServiceAPI.py", line 57, in getListAllUserDevices
    resultLists = res["result"][0]["list"]
KeyError: 0
```

**Comment by sxx1314** [comment]
现在 又
