### ISSUE TITLE
getListAllUserDevices的API失效问题

### ISSUE THREAD

**Issue by sxx1314** [leifengwl/JDRouterPush#31]
如果是白天运行具体时间段不确定，大概是0点到8点。
GlobalVariable.jd_service_url + "listAllUserDevices"  这个接口就会报错。
```
Traceback (most recent call last):
  File "JDRouterPush.py", line 295, in <module>
    main()
  File "JDRouterPush.py", line 288, in main
    todayPointDetail()
  File "JDRouterPush.py", line 121, in todayPointDetail
    JDServiceAPI.getListAllUserDevices()
  File "/mnt/mmc0/work/JDRouterPush/JDServiceAPI.py", line 57, in getListAllUserDevices
    resultLists = res["result"][0]["list"]
KeyError: 0
```
直接输出返回的json发现
```
{'result': {}, 'error': {'errorInfo': 'token invalid', 'errorCode': '401'}, 'status': 100}
```

但是如果中午12点之后运行又没有问题。

最后抓包发现是时间不对。
默认time使用utc时间,改成系统时间解决问题（系统时间东八区）
```
time = datetime.datetime.unow().strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z"
```
因为我是本地运行，actions应该本身本地时间就是utc时间吧可能不会报错。

**Comment by leifengwl** [comment]
actions使用的是utc时间 ，本地的话我没在八点前测试过，抓包是本地时间发送的，当时遗漏了这个问题，谢谢
