### ISSUE TITLE
今天推送出现错误

### ISSUE THREAD

**Issue by kennylee60** [leifengwl/JDRouterPush#44]
Run python JDRouterPush.py
Traceback (most recent call last):
欢迎使用JDRouterPush!
  File "/home/runner/work/JDRouterPush/JDRouterPush/JDRouterPush.py", line 294, in <module>
Request routerActivityInfo failed!
    main()
  File "/home/runner/work/JDRouterPush/JDRouterPush/JDRouterPush.py", line 289, in main
    resultDisplay()
  File "/home/runner/work/JDRouterPush/JDRouterPush/JDRouterPush.py", line 230, in resultDisplay
    point_infos +=  "\n    - 当前网速：" + pointInfo["speed"] \
KeyError: 'speed'
Request routerActivityInfo failed!
Request routerActivityInfo failed!
无法获取插件信息!
信息如下: 
无法获取插件信息!
信息如下: 
无法获取插件信息!
信息如下: 
Request getControlDevice failed!
Request getControlDevice failed!
Error: Process completed with exit code 1.

**Comment by leifengwl** [comment]
设备不在线导致的   没有开机或者没有联网

**Comment by kennylee60** [comment]
> 设备不在线导致的 没有开机或者没有联网

在线的啊

**Comment by leifengwl** [comment]
> > 设备不在线导致的 没有开机或者没有联网
> 
> 在线的啊

现在运行是否正常呢？这情况出现过一次还是多次

**Comment by kennylee60** [comment]
> > > 设备不在线导致的 没有开机或者没有联网
> > 
> > 
> > 在线的啊
> 
> 现在运行是否正常呢？这情况出现过一次还是多次

过了几天又正常了
