### ISSUE TITLE
这几天没推送，看了下报错好多，啥都没改，不知道啥原因

### ISSUE THREAD

**Issue by xy364515640** [leifengwl/JDRouterPush#50]
Run python JDRouterPush.py
  python JDRouterPush.py
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.9.5/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.5/x64/lib
    WSKEY: ***
    DEVICENAME: 
    RECORDSNUM: 
    SERVERPUSHKEY: ***
    TG_BOT_TOKEN: 
    TG_USER_ID: 
    BARK: 
    PUSHPLUS: ***
    ACCESSTOKEN: 
    CORPID: 
    CORPSECRET: 
    TOUSER: 
    AGENTID: 
    THUMB_MEDIA_ID: 
    AUTHOR: 
Traceback (most recent call last):
欢迎使用JDRouterPush!
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
Request routerActivityInfo failed!
    httplib_response = self._make_request(
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/http/client.py", line 1345, in getresponse
无法获取插件信息!
信息如下: 
    response.begin()
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/http/client.py", line 1345, in getresponse
    response.begin()
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/JDRouterPush/JDRouterPush/JDRouterPush.py", line 294, in <module>
    main()
  File "/home/runner/work/JDRouterPush/JDRouterPush/JDRouterPush.py", line 289, in main
    resultDisplay()
  File "/home/runner/work/JDRouterPush/JDRouterPush/JDRouterPush.py", line 259, in resultDisplay
    NoticePush.server_push(title, markdownContent.replace("- ***", "```"))
  File "/home/runner/work/JDRouterPush/JDRouterPush/NoticePush.py", line 19, in server_push
    res = requests.post(url=server_push_url, data=params)
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/requests/sessions.py", line 677, in send
    history = [resp for resp in gen]
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/requests/sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/requests/sessions.py", line 237, in resolve_redirects
    resp = self.send(
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error: Process completed with exit code 1.

**Comment by leifengwl** [comment]
设备是否正常运行？

**Comment by xy364515640** [comment]
> 设备是否正常运行？

是的，无任何改动。

**Comment by leifengwl** [comment]
已更新
