### ISSUE TITLE
还更新吗，今天开始又不能推送了

### ISSUE THREAD

**Issue by kennylee60** [leifengwl/JDRouterPush#52]
Run python JDRouterPush.py
Traceback (most recent call last):
欢迎使用JDRouterPush!
  File "/home/runner/work/JDRouterPush/JDRouterPush/JDRouterPush.py", line 294, in <module>
Request routerActivityInfo failed!
Request routerActivityInfo failed!
Request routerActivityInfo failed!
无法获取插件信息!
信息如下: 
无法获取插件信息!
信息如下: 
    main()
  File "/home/runner/work/JDRouterPush/JDRouterPush/JDRouterPush.py", line 289, in main
    resultDisplay()
  File "/home/runner/work/JDRouterPush/JDRouterPush/JDRouterPush.py", line 230, in resultDisplay
    point_infos +=  "\n    - 当前网速：" + pointInfo["speed"] \
KeyError: 'speed'
Request getControlDevice failed!
Request getControlDevice failed!
Error: Process completed with exit code 1.

出现这个提示

**Comment by leifengwl** [comment]
已更新
