### ISSUE TITLE
突然不能正常推送了

### ISSUE THREAD

**Issue by name2008less** [leifengwl/JDRouterPush#53]
Run python JDRouterPush.py
2
  python JDRouterPush.py
3
  shell: /usr/bin/bash -e {0}
4
  env:
5
    pythonLocation: /opt/hostedtoolcache/Python/3.9.5/x64
6
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.5/x64/lib
7
    WSKEY: ***
8
    DEVICENAME: 
9
    RECORDSNUM: 
10
    SERVERPUSHKEY: 
11
    TG_BOT_TOKEN: 
12
    TG_USER_ID: 
13
    BARK: 
14
    PUSHPLUS: 
15
    ACCESSTOKEN: 
16
    CORPID: ***
17
    CORPSECRET: ***
18
    TOUSER: ***
19
    AGENTID: ***
20
    THUMB_MEDIA_ID: ***
21
    AUTHOR: ***
22
欢迎使用JDRouterPush!
23
Traceback (most recent call last):
24
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
25
    httplib_response = self._make_request(
26
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
27
    self._validate_conn(conn)
28
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
29
    conn.connect()
30
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/urllib3/connection.py", line 411, in connect
31
    self.sock = ssl_wrap_socket(
32
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
33
    ssl_sock = _ssl_wrap_socket_impl(
34
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
35
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
36
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/ssl.py", line 500, in wrap_socket
37
    return self.sslsocket_class._create(
38
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/ssl.py", line 1040, in _create
39
    self.do_handshake()
40
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/ssl.py", line 1309, in do_handshake
41
    self._sslobj.do_handshake()
42
ConnectionResetError: [Errno 104] Connection reset by peer
43

44
During handling of the above exception, another exception occurred:
45

46
Traceback (most recent call last):
47
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
48
    resp = conn.urlopen(
49
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
50
    retries = retries.increment(
51
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/urllib3/util/retry.py", line 532, in increment
52
    raise six.reraise(type(error), error, _stacktrace)
53
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/urllib3/packages/six.py", line 769, in reraise
54
    raise value.with_traceback(tb)
55
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
56
    httplib_response = self._make_request(
57
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
58
    self._validate_conn(conn)
59
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
60
    conn.connect()
61
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/urllib3/connection.py", line 411, in connect
62
    self.sock = ssl_wrap_socket(
63
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
64
    ssl_sock = _ssl_wrap_socket_impl(
65
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
66
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
67
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/ssl.py", line 500, in wrap_socket
68
    return self.sslsocket_class._create(
69
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/ssl.py", line 1040, in _create
70
    self.do_handshake()
71
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/ssl.py", line 1309, in do_handshake
72
    self._sslobj.do_handshake()
73
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
74

75
During handling of the above exception, another exception occurred:
76

77
Traceback (most recent call last):
78
  File "/home/runner/work/push/push/JDRouterPush.py", line 294, in <module>
79
    main()
80
  File "/home/runner/work/push/push/JDRouterPush.py", line 286, in main
81
    todayPointIncome()
82
  File "/home/runner/work/push/push/JDRouterPush.py", line 16, in todayPointIncome
83
    res = requests.get(GlobalVariable.jd_base_url + "todayPointIncome", headers=GlobalVariable.headers)
84
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/requests/api.py", line 76, in get
85
    return request('get', url, params=params, **kwargs)
86
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/requests/api.py", line 61, in request
87
    return session.request(method=method, url=url, **kwargs)
88
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
89
    resp = self.send(prep, **send_kwargs)
90
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
91
    r = adapter.send(request, **kwargs)
92
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/requests/adapters.py", line 498, in send
93
    raise ConnectionError(err, request=request)
94
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
95
Error: Process completed with exit code 1.

**Comment by name2008less** [comment]
手动执行后依然报错


Run python JDRouterPush.py
2
  python JDRouterPush.py
3
  shell: /usr/bin/bash -e {0}
4
  env:
5
    pythonLocation: /opt/hostedtoolcache/Python/3.9.5/x64
6
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.5/x64/lib
7
    WSKEY: ***
8
    DEVICENAME: 
9
    RECORDSNUM: 
10
    SERVERPUSHKEY: 
11
    TG_BOT_TOKEN: 
12
    TG_USER_ID: 
13
    BARK: 
14
    PUSHPLUS: 
15
    ACCESSTOKEN: 
16
    CORPID: ***
17
    CORPSECRET: ***
18
    TOUSER: ***
19
    AGENTID: ***
20
    THUMB_MEDIA_ID: ***
21
    AUTHOR: ***
22
Traceback (most recent call last):
23
欢迎使用JDRouterPush!
24
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
25
    httplib_response = self._make_request(
26
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
27
    self._validate_conn(conn)
28
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
29
    conn.connect()
30
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/urllib3/connection.py", line 411, in connect
31
    self.sock = ssl_wrap_socket(
32
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
33
    ssl_sock = _ssl_wrap_socket_impl(
34
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
35
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
36
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/ssl.py", line 500, in wrap_socket
37
    return self.sslsocket_class._create(
38
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/ssl.py", line 1040, in _create
39
    self.do_handshake()
40
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/ssl.py", line 1309, in do_handshake
41
    self._sslobj.do_handshake()
42
ConnectionResetError: [Errno 104] Connection reset by peer
43

44
During handling of the above exception, another exception occurred:
45

46
Traceback (most recent call last):
47
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
48
    resp = conn.urlopen(
49
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
50
    retries = retries.increment(
51
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/urllib3/util/retry.py", line 532, in increment
52
    raise six.reraise(type(error), error, _stacktrace)
53
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/urllib3/packages/six.py", line 769, in reraise
54
    raise value.with_traceback(tb)
55
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
56
    httplib_response = self._make_request(
57
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
58
    self._validate_conn(conn)
59
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
60
    conn.connect()
61
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/urllib3/connection.py", line 411, in connect
62
    self.sock = ssl_wrap_socket(
63
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
64
    ssl_sock = _ssl_wrap_socket_impl(
65
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
66
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
67
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/ssl.py", line 500, in wrap_socket
68
    return self.sslsocket_class._create(
69
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/ssl.py", line 1040, in _create
70
    self.do_handshake()
71
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/ssl.py", line 1309, in do_handshake
72
    self._sslobj.do_handshake()
73
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
74

75
During handling of the above exception, another exception occurred:
76

77
Traceback (most recent call last):
78
  File "/home/runner/work/push/push/JDRouterPush.py", line 294, in <module>
79
    main()
80
  File "/home/runner/work/push/push/JDRouterPush.py", line 286, in main
81
    todayPointIncome()
82
  File "/home/runner/work/push/push/JDRouterPush.py", line 16, in todayPointIncome
83
    res = requests.get(GlobalVariable.jd_base_url + "todayPointIncome", headers=GlobalVariable.headers)
84
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/requests/api.py", line 76, in get
85
    return request('get', url, params=params, **kwargs)
86
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/requests/api.py", line 61, in request
87
    return session.request(method=method, url=url, **kwargs)
88
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
89
    resp = self.send(prep, **send_kwargs)
90
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
91
    r = adapter.send(request, **kwargs)
92
  File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/requests/adapters.py", line 498, in send
93
    raise ConnectionError(err, request=request)
94
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
95
Error: Process completed with exit code 1.

**Comment by name2008less** [comment]
第二次手动运行终于成功了

**Comment by leifengwl** [comment]
已更新
